# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.emp:
        class: AppBundle\Controller\Biblioteca
        calls:
                    - [setContainer, ["@service_container"]]

    form_authenticator:
          class: AppBundle\Controller\FormAuthenticator
          arguments: ['@doctrine.orm.entity_manager', '@router']

    app.lancamento:
        class: AppBundle\Controller\LancamentosController
        calls:
                    - [setContainer, ["@service_container"]]